POST http://localhost:3001/api/users
Content-Type: application/json

{
  "userName": "Trinity",
  "avatarURI": "https://i.imgur.com/eAHn3r3.jpg",
  "bio": "Matrix (1999)",
  "isBot": false
}
###

GET http://localhost:3001/api/users/Neo
Content-Type: application/json
###
